# Generated by Django 2.1.5 on 2019-07-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_pinyin', models.CharField(max_length=20)),
                ('city_url', models.CharField(max_length=255)),
            ],
        ),
    ]
