# Generated by Django 2.1.5 on 2019-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uju', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_pinyin',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
