# Generated by Django 2.1.5 on 2019-07-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uju', '0003_auto_20190701_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_pinyin',
            field=models.CharField(max_length=100),
        ),
    ]
